"""Add Google AI settings

Revision ID: a1b2c3d4e5f6
Revises: 1d9a002d7234
Create Date: 2025-12-20 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '1d9a002d7234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    op.add_column('site_settings', sa.Column('ai_provider', sa.String(), nullable=True, server_default='openai'))
    op.add_column('site_settings', sa.Column('google_api_key', sa.String(), nullable=True))
    op.add_column('site_settings', sa.Column('google_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_column('site_settings', 'google_model')
    op.drop_column('site_settings', 'google_api_key')
    op.drop_column('site_settings', 'ai_provider')
    # ### end Alembic commands ###
